exports.MISSING_PARAMETERS = {code: 100, message: "Missing information."};
exports.DATABASE = {code: 107, message: "Database error."};
exports.EMAIL_ALREADY_EXISTS = {code: 201, message: "Email already exists."};
exports.USERNAME_ALREADY_EXISTS = {code: 202, message: "Username already exists."};
exports.INVALID_CREDENTIALS = {code: 205, message: "Invalid username or password."};
exports.INVALID_EMAIL = {code: 206, message: "The email was not found."};
exports.USER_NOT_VERIFIED = {code: 207, message: "The email is not verified."};
exports.INVALID_RESET_CODE = {code: 208, message: "The reset code is invalid or has expired."};
exports.INVALID_VERIFICATION_CODE = {code: 209, message: "The verification code is invalid or has expired."};
exports.USER_IS_VERIFIED = {code: 210, message: "The email is already verified."};
exports.INVALID_TOKEN = {code: 301, message: "The token is invalid or has expired."};
exports.INVALID_CONNECTION = {code: 302, message: "The specified user is not a connection."}
exports.INVALID_CHATID = {code: 303, message: "This user already belongs to the specified chat."}